# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "Corne42_XiaoBle"
product_name = "Corne42_XiaoBle"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "Andy"
board = "XIAO BLE"

[layout]
rows = 4
cols = 12
layers = 3
keymap = [
    [
        ["_", "_", "_","_","_","_","_","_","_","_","_","_"],
        ["_", "_", "_","_","_","_","_","_","_","_","_","_"],
        ["_", "_", "_","_","_","_","_","_","_","_","_","_"],
        ["_", "_", "_","_","_","_","_","_","_","_","_","_"]
    ],
    [
        ["_", "_", "_","_","_","_","_","_","_","_","_","_"],
        ["_", "_", "_","_","_","_","_","_","_","_","_","_"],
        ["_", "_", "_","_","_","_","_","_","_","_","_","_"],
        ["_", "_", "_","_","_","_","_","_","_","_","_","_"]
    ],
    [
        ["_", "_", "_","_","_","_","_","_","_","_","_","_"],
        ["_", "_", "_","_","_","_","_","_","_","_","_","_"],
        ["_", "_", "_","_","_","_","_","_","_","_","_","_"],
        ["_", "_", "_","_","_","_","_","_","_","_","_","_"]
    ],
]

[split]
connection = "ble"
[ble]
enabled = true
battery_adc_pin = "vddh"


[split.central]
rows = 4
cols = 6
row_offset = 0
col_offset = 0
ble_addr = [0x18, 0xe2, 0x21, 0x80, 0xc0, 0xc7]

[split.central.matrix]
matrix_type = "normal"
# RMK uses col2row as the default matrix diode direction, if you want to use a row2col matrix, add `row2col = true`
# row2col = true
row_pins = ["P0_02", "P0_03", "P0_28", "P0_29"]
col_pins = ["P1_11", "P1_12", "P1_13", "P1_14", "P1_15", "P0_10"]

[[split.peripheral]]
rows = 4
cols = 6
row_offset = 0
col_offset = 6
ble_addr = [0x7e, 0xfe, 0x73, 0x9e, 0x66, 0xe3]

[split.peripheral.matrix]
matrix_type = "normal"
row_pins = ["P0_02", "P0_03", "P0_28", "P0_29"]
col_pins = ["P1_11", "P1_12", "P1_13", "P1_14", "P1_15", "P0_10"]

nfc-pins-as-gpio = ["P_10"]

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true

[storage]
# Storage feature is enabled by default
# enabled = false

[rmk]

# # Mouse key interval (ms) - controls mouse movement speed
# mouse_key_interval = 20
# # Mouse wheel interval (ms) - controls scrolling speed
# mouse_wheel_interval = 80
# # Maximum number of combos keyboard can store
# combo_max_num = 8
# # Maximum number of keys pressed simultaneously in a combo
# combo_max_length = 4
# # Maximum number of forks for conditional key actions
# fork_max_num = 8
# # Maximum number of morse keys keyboard can store (max 256)
# morse_max_num = 8
# # Maximum number of patterns a morse key can handle (default: 8, min: 4, max 65536)
# max_patterns_per_key = 8
# # Macro space size in bytes for storing sequences. The maximum number of Macros depends on the size of each sequence: All sequences combined need to fit into macro_space_size, the number of macro sequences doesn't matter.
# macro_space_size = 256
# # Default debounce time in ms
# debounce_time = 20
# # Event channel size
# event_channel_size = 16
# # Controller event channel size
# controller_channel_size = 16
# # Number of publishers to controllers
# controller_channel_pubs = 12
# # Number of controllers (subscribers)
# controller_channel_subs = 8
# # Report channel size
# report_channel_size = 16

# Vial channel size
vial_channel_size = 4
# Flash channel size
flash_channel_size = 4
# The number of the split peripherals
split_peripherals_num = 1
# The number of available BLE profiles
ble_profiles_num = 8
# BLE Split Central sleep timeout in seconds (0 = disabled)
split_central_sleep_timeout_seconds = 0

